#!/usr/bin/env bash

# Quick Admin Setup Script for NowInTown
# This script helps you set up the admin user and environment

echo "==================================="
echo "NowInTown - Admin Setup Script"
echo "==================================="
echo ""

echo "This script will help you set up:"
echo "1. Admin email environment variable in Supabase"
echo "2. Admin role for your user in the database"
echo ""

# Admin email
ADMIN_EMAIL="shivan.meymo@gmail.com"
echo "✓ Admin Email: $ADMIN_EMAIL"
echo ""

echo "==================================="
echo "Step 1: Supabase Environment Variable"
echo "==================================="
echo ""
echo "Go to your Supabase Dashboard and add this environment variable:"
echo ""
echo "Variable Name:  ADMIN_EMAIL"
echo "Variable Value: $ADMIN_EMAIL"
echo ""
echo "Path: Dashboard → Settings → Edge Functions → Add Secret"
echo ""
read -p "Press Enter when you've added the environment variable..."

echo ""
echo "==================================="
echo "Step 2: Find Your Firebase UID"
echo "==================================="
echo ""
echo "You need your Firebase User ID (UID) to grant admin access."
echo "Choose one of these methods:"
echo ""
echo "Method 1: Firebase Console"
echo "  1. Go to https://console.firebase.google.com/"
echo "  2. Select your project"
echo "  3. Go to Authentication → Users"
echo "  4. Find: $ADMIN_EMAIL"
echo "  5. Copy the User UID"
echo ""
echo "Method 2: From your app (easiest)"
echo "  1. Log in to your app with $ADMIN_EMAIL"
echo "  2. Open Browser DevTools (F12)"
echo "  3. Go to Console tab"
echo "  4. Look for a log that shows your user ID"
echo ""
echo "Method 3: Check database"
echo "  1. Go to Supabase SQL Editor"
echo "  2. Run: SELECT DISTINCT user_id FROM public.events WHERE user_id IS NOT NULL LIMIT 10;"
echo "  3. Find your user_id"
echo ""
read -p "Enter your Firebase UID: " FIREBASE_UID

if [ -z "$FIREBASE_UID" ]; then
  echo "❌ Error: Firebase UID is required"
  exit 1
fi

echo ""
echo "==================================="
echo "Step 3: Grant Admin Role"
echo "==================================="
echo ""
echo "Copy and run this SQL in your Supabase SQL Editor:"
echo ""
echo "---------------------------------------"
echo "-- Grant admin role to your user"
echo "INSERT INTO public.user_roles (user_id, role)"
echo "VALUES ('$FIREBASE_UID', 'admin')"
echo "ON CONFLICT (user_id, role) DO NOTHING;"
echo ""
echo "-- Verify admin role"
echo "SELECT * FROM public.user_roles WHERE user_id = '$FIREBASE_UID';"
echo "---------------------------------------"
echo ""
read -p "Press Enter when you've run the SQL..."

echo ""
echo "==================================="
echo "Setup Complete! 🎉"
echo "==================================="
echo ""
echo "What you can do now:"
echo "✓ Receive email notifications for new events"
echo "✓ Access the admin dashboard at /admin"
echo "✓ Approve or reject events"
echo "✓ Edit any event (not just your own)"
echo "✓ View event statistics"
echo ""
echo "Next steps:"
echo "1. Log out and log back in to your app"
echo "2. Navigate to: https://your-domain.com/admin"
echo "3. Create a test event to verify email notifications"
echo ""
echo "Troubleshooting:"
echo "- Not receiving emails? Check Edge Functions logs in Supabase"
echo "- Can't access /admin? Verify user_roles table has your admin role"
echo "- Clear browser cache and cookies if you have issues"
echo ""
echo "For more details, see: ADMIN_SETUP.md"
echo ""
