-- Spontaneous activities and group chat schema
-- NOTE: This migration creates tables and RLS policies to support
-- user-created spontaneous activities with per-activity anonymous nicknames
-- and a group chat tied to the activity. Only members can read/write the chat.

-- 1) Activities
create table if not exists public.activities (
  id uuid primary key default gen_random_uuid(),
  creator_id uuid not null references auth.users(id) on delete cascade,
  title text not null,
  description text,
  category text not null default 'spontaneous',
  location text,
  starts_at timestamptz,
  ends_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint activities_category_check check (category in ('spontaneous'))
);

create index if not exists idx_activities_creator on public.activities(creator_id);
create index if not exists idx_activities_category on public.activities(category);

-- 2) Memberships with per-activity anonymous nickname
create table if not exists public.activity_members (
  activity_id uuid not null references public.activities(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  nickname text not null,
  role text not null default 'member', -- 'creator' | 'member'
  joined_at timestamptz not null default now(),
  primary key (activity_id, user_id),
  constraint activity_members_role_check check (role in ('creator','member'))
);

create index if not exists idx_activity_members_user on public.activity_members(user_id);

-- 3) Messages for the group chat
create table if not exists public.activity_messages (
  id bigint generated by default as identity primary key,
  activity_id uuid not null references public.activities(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  content text,
  image_url text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint activity_messages_content_or_image check (
    (content is not null and length(trim(content)) > 0) or image_url is not null
  )
);

create index if not exists idx_activity_messages_activity on public.activity_messages(activity_id);
create index if not exists idx_activity_messages_user on public.activity_messages(user_id);
create index if not exists idx_activity_messages_created on public.activity_messages(created_at);

-- 4) Row Level Security
alter table public.activities enable row level security;
alter table public.activity_members enable row level security;
alter table public.activity_messages enable row level security;

-- Activities policies
-- Select: public can view basic info to discover activities (or restrict to authenticated)
create policy if not exists activities_select_public
  on public.activities for select
  using (true);

-- Insert: authenticated users can create activities
create policy if not exists activities_insert_auth
  on public.activities for insert
  to authenticated
  with check (auth.uid() = creator_id);

-- Update/Delete: only creator can modify/delete
create policy if not exists activities_update_creator
  on public.activities for update
  to authenticated
  using (auth.uid() = creator_id)
  with check (auth.uid() = creator_id);

create policy if not exists activities_delete_creator
  on public.activities for delete
  to authenticated
  using (auth.uid() = creator_id);

-- Membership policies
-- Select: only members of the activity can see the membership list (preserves anonymity outside)
create policy if not exists activity_members_select_members
  on public.activity_members for select
  to authenticated
  using (
    exists (
      select 1 from public.activity_members am
      where am.activity_id = activity_members.activity_id
        and am.user_id = auth.uid()
    )
  );

-- Insert: allow self-join or creator to add someone (creator flow). Default: self-join
create policy if not exists activity_members_insert_self
  on public.activity_members for insert
  to authenticated
  with check (
    user_id = auth.uid()
  );

-- Update: members can update their own nickname; creator can update any member role/nickname
create policy if not exists activity_members_update_self_or_creator
  on public.activity_members for update
  to authenticated
  using (
    user_id = auth.uid() or
    exists (
      select 1 from public.activities a
      where a.id = activity_members.activity_id and a.creator_id = auth.uid()
    )
  )
  with check (
    user_id = auth.uid() or
    exists (
      select 1 from public.activities a
      where a.id = activity_members.activity_id and a.creator_id = auth.uid()
    )
  );

-- Delete: member can leave; creator can remove members
create policy if not exists activity_members_delete_self_or_creator
  on public.activity_members for delete
  to authenticated
  using (
    user_id = auth.uid() or
    exists (
      select 1 from public.activities a
      where a.id = activity_members.activity_id and a.creator_id = auth.uid()
    )
  );

-- Messages policies
-- Select: only members of the activity can read messages
create policy if not exists activity_messages_select_members
  on public.activity_messages for select
  to authenticated
  using (
    exists (
      select 1 from public.activity_members am
      where am.activity_id = activity_messages.activity_id
        and am.user_id = auth.uid()
    )
  );

-- Insert: only members can send messages
create policy if not exists activity_messages_insert_members
  on public.activity_messages for insert
  to authenticated
  with check (
    exists (
      select 1 from public.activity_members am
      where am.activity_id = activity_messages.activity_id
        and am.user_id = auth.uid()
    )
  );

-- Update/Delete: author can edit/delete own; creator can moderate all
create policy if not exists activity_messages_update_self_or_creator
  on public.activity_messages for update
  to authenticated
  using (
    user_id = auth.uid() or
    exists (
      select 1 from public.activities a
      where a.id = activity_messages.activity_id and a.creator_id = auth.uid()
    )
  )
  with check (
    user_id = auth.uid() or
    exists (
      select 1 from public.activities a
      where a.id = activity_messages.activity_id and a.creator_id = auth.uid()
    )
  );

create policy if not exists activity_messages_delete_self_or_creator
  on public.activity_messages for delete
  to authenticated
  using (
    user_id = auth.uid() or
    exists (
      select 1 from public.activities a
      where a.id = activity_messages.activity_id and a.creator_id = auth.uid()
    )
  );

-- 5) Helpers
-- When creating an activity, also insert a membership for the creator with a nickname
create or replace function public.create_activity(
  p_title text,
  p_description text,
  p_location text,
  p_starts_at timestamptz,
  p_ends_at timestamptz,
  p_creator_nickname text
) returns public.activities
language plpgsql
security definer
as $$
declare
  v_activity public.activities;
begin
  insert into public.activities (creator_id, title, description, location, starts_at, ends_at)
  values (auth.uid(), p_title, p_description, p_location, p_starts_at, p_ends_at)
  returning * into v_activity;

  insert into public.activity_members(activity_id, user_id, nickname, role)
  values (v_activity.id, auth.uid(), coalesce(p_creator_nickname, 'Creator'), 'creator');

  return v_activity;
end;
$$;